"""A fake Ollama for tests: /api/version, /api/tags and /api/show only. Anything that would load or
download a model (/api/chat, /api/generate, /api/pull) fails the test."""
import hashlib
import io
import json
import urllib.error

NANO_GGUF = "be5d9a656a51922f24f1f09a759cebb694e1f5d9728bf0ef9f8c972c5a0b5ef2"   # measured (AgentDojo 4B)
QWEN_9B = "dec52a44569a2a25341c4e4d3fee25846eed4f6f0b936278e3a3c900bb99d37c"     # measured (AgentDojo Qwen)
OTHER = "ab" * 32                                                                     # not measured


def manifest_of(blob: str) -> str:
    return blob[::-1]          # any distinct 64-hex string will do


class FakeOllama:
    def __init__(self, tags=(), up=True, blobs=None, no_digest=False):
        """tags: model names on disk. blobs: {name: weights hex} (default: a per-name made-up hex)."""
        self.tags, self.up, self.blobs, self.no_digest = list(tags), up, dict(blobs or {}), no_digest
        self.urls, self.manifests = [], {}

    def blob(self, name):
        return self.blobs.get(name) or hashlib.sha256(name.encode()).hexdigest()

    def manifest(self, name):
        return self.manifests.get(name) or manifest_of(self.blob(name))

    def __call__(self, req, timeout=None):
        url = getattr(req, "full_url", req)
        self.urls.append(url)
        if not self.up:
            raise urllib.error.URLError("connection refused")
        if url.endswith("/api/version"):
            body = {"version": "0.35.0"}
        elif url.endswith("/api/tags"):
            body = {"models": [{"name": t, "size": 2837597147,
                                **({} if self.no_digest else {"digest": self.manifest(t)})} for t in self.tags]}
        elif url.endswith("/api/show"):
            name = json.loads(req.data)["model"]
            norm = lambda t: t if ":" in t else t + ":latest"
            name = next((t for t in self.tags if norm(t) == norm(name)), None)
            if name is None:
                raise urllib.error.HTTPError(url, 404, "not found", {}, None)
            body = {"modelfile": f"# Modelfile generated by \"ollama show\"\n# FROM {name}\n\n"
                                 f"FROM /Users/x/.ollama/models/blobs/sha256-{self.blob(name)}\n"
                                 "TEMPLATE {{ .Prompt }}\n"}
        else:
            raise AssertionError(f"tests must not call {url}")
        return io.BytesIO(json.dumps(body).encode())
